POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hbWUiLCJpZCI6IjY0MjQ3YjZiODk4NGQyN2M2ODg2MTNkZiIsImlhdCI6MTY4MDExMzA5N30.VCC85epIkvtbYBH2UKltCagZz0z7XshkAvp_aacEX60

{
  "title": "testing a blog post with token and user extractor.",
  "author": "edaa",
  "url": "www.c7.com",
  "likes": 4
}